### ISSUE TITLE
Is parallel build of sass and Eleventy safe?

### ISSUE THREAD

**Issue by nhoizey** [5t3ph/11ty-sass-skeleton#1]
I see the `build` script runs `build:sass` and `build:eleventy` in parallel.

Is there no risk Eleventy uses a previous version of the sass build, if it runs faster?

**Comment by 5t3ph** [comment]
Hi @nhoizey - in my experience running this same setup on several other projects, the scripts are run in the order (top to bottom) as listed in the package, which is why eleventy is listed last in both the `watch` and `build` series of commands 👍 So order wins over speed. Closing, but re-open an issue if you encounter it not working that way, although searching for specifically `npm-run-all` may answer more of your questions on the build order processing.

**Comment by nhoizey** [comment]
Thanks for the answer.

I guess you always have a faster CSS build than Eleventy build then, because `--parallel` really run both in parallel.

I'll try with `--sequential` anyway.

Thanks again.

**Comment by 5t3ph** [comment]
@nhoizey I hit the issue you were talking about and finally understood what you mean :) I've updated the build process on this repo, as seen here in case it helps you as well: https://github.com/5t3ph/11ty-sass-skeleton/commit/a3c42682ae96259e831152734746fc10195dd806

Basically - switching to directly dump the sass in public, and the `postbuild` happens on `public` as well.

**Comment by nhoizey** [comment]
@5t3ph good improvement! 👍
